Display Links beneath associated Teleporters
allejo/WebBZEdit pull request #19
Opened 2021-06-23 19:20 UTC by sorayadragon

Closes #16 

Displays the links associated with a Teleporter's Front and Back sides with arrows indicating if it's an Incoming or Outgoing link.
![image](https://user-images.githubusercontent.com/38041869/123155746-7ddead80-d436-11eb-9c27-1dbf95ece7a4.png)

2021-06-24 05:02 UTC, allejo requested changes
Solid implementation 👍 Just some minor refactoring needed

2021-06-24 05:02 UTC, allejo commented on src/Components/Panels/Inventory/LinkSummary.tsx
> +                })}
```suggestion
              {links.map((link, i) => {
                const isFromTele = link.from.name === tele.name;
                const teleRef = isFromTele ? link.to : link.from;
                const icon = isFromTele
                  ? faLongArrowAltRight
                  : faLongArrowAltLeft;

                return (
                  <li key={`${tele.name}-link${i}`}>
                    <FontAwesomeIcon icon={icon} /> {teleRef.name}:
                    {teleRef.side}
                  </li>
                );
              })}
```

Not sure if this was because I misspoke in a previous PR, but you could totally use a ternary here to simplify the JSX since it's just an "either/or" case; there aren't any nested ternaries.

2021-06-24 05:02 UTC, allejo commented on src/Components/Panels/Inventory/LinkSummary.tsx
> +  ({ object }: Props, ref) => {
Similar to Vue's template refs, React has refs to access DOM elements directly. `ObstacleSummary` uses a ref so that the Inventory panel can be scrolled to a point where the selected object is in view. Since `LinkSummary` is being used inside of the `ObstacleSummary` and there's nothing special that we need to do with the `<div>` that this component renders, there's no need to forward any refs or use refs in here.

i.e. This would be enough,

```ts
const LinkSummary = ({ object }: Props) => {
  // ...
};
```

2021-06-24 05:02 UTC, allejo commented on src/Document/parseBZWDocument.ts
> +      }
Instead of adding this inside of the main parsing function, let's move this to the `link`'s `finalize` function in our `ObjectBuilders` dictionary. Change the signature of `finalize` in `ObjectBuilder` to be `(obstacle: any, world: IWorld) => void`. Then feed the `world` object when `finalize` is called right above this block.

2021-06-24 14:28 UTC, sorayadragon commented on src/Components/Panels/Inventory/LinkSummary.tsx
> +                })}
Ok! I thought you might like the if/else better there for clarity.

2021-06-24 14:29 UTC, sorayadragon commented on src/Components/Panels/Inventory/LinkSummary.tsx
> +  ({ object }: Props, ref) => {
I had it that way, but it was complaining that I'd forgotten the ref attribute, so I just added it in. The warning went away and it didn't complain that it was never being used. lol

2021-06-24 14:30 UTC, sorayadragon commented on src/Document/parseBZWDocument.ts
> +      }
Ah, great idea! I forgot about that function.

2021-06-25 06:11 UTC, allejo requested changes

2021-06-25 06:11 UTC, allejo commented on src/Components/Panels/Inventory/LinkSummary.tsx
> +const LinkSummary = forwardRef<HTMLDivElement, Props>(({ object }: Props) => {
No need for the `forwardRef` function call. Just make the `LinkSummary` an arrow function, not a component with a forwarded ref.

```suggestion
const LinkSummary = ({ object }: Props) => {
```

2021-06-25 23:14 UTC, allejo approved these changes
LGTM 🥳

2021-06-26 00:07 UTC, allejo commented
Gonna merge this one so that `feature/rename-objects` can be rebased

2021-06-26 00:08 UTC, merged