Add toolbox component for changing passability of objects
allejo/WebBZEdit pull request #4
Opened 2021-05-29 07:22 UTC by Adwitiya-Singh

Add front-end capabilities to change passability values of objects

2021-05-29 08:07 UTC, allejo approved these changes
Glad to see it works 😄 Here are some semantic changes needed

2021-05-29 08:07 UTC, allejo commented on src/Components/Panels/ToolboxPanel.tsx
> +import PassabilityControls from './Toolbox/PassabilityControl';
```suggestion
import PassabilityControls from './Toolbox/PassabilityControls';
```

2021-05-29 08:07 UTC, allejo commented on src/Components/Panels/ToolboxPanel.tsx
> +      obstacle.passable = data.passable;
```suggestion
```

No need to set the `passable` attribute as this will automatically return the correct value based on the values of `shootthrough` and `drivethrough`.

2021-05-29 08:07 UTC, allejo commented on src/Components/Panels/ToolboxPanel.tsx
> +      )}
Can you put this to the right of the PositionableContols? (i.e. move it after)

2021-05-29 08:07 UTC, allejo commented on src/Components/Panels/Toolbox/PassabilityControl.tsx
> +  };
```suggestion
  const handleDriveThroughOnChange = () => {
    onChange({
      ...data,
      drivethrough: !data.drivethrough,
    });
  };
```

If you're not going to use an argument, you can just omit it. Only use `_` if it's like a middle argument or it needs to be saved to a variable for some reason.

Also, no need for an intermediary variable. You only need an intermediary variable if it's doing some type of logic or is evaluating to a boolean value that isn't straightforward. e.g.

```js
const isShiftRequiredAndHeld = requirement.shift && event.shiftKey;
```

---

Same thing for shootthrough

2021-05-29 08:07 UTC, allejo commented on src/Components/Panels/Toolbox/PassabilityControl.tsx
> +        <label htmlFor="shootthrough">Pass Through</label>
```suggestion
        <label htmlFor="shootthrough">Shoot Through</label>
```

2021-05-29 08:07 UTC, allejo commented on src/Components/Panels/Toolbox/PassabilityControl.tsx
> +    <div className={styles.wrapper}>
```suggestion
    <fieldset className={styles.wrapper}>
```

Let's make this a [`<fieldset>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset). It's useful for grouping related input fields.

Semi-related: the [`<legend>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/legend) tag can **only** exist inside of a `<fieldset>`; since you had it inside of a `<div>`, it doesn't make semantically.

2021-05-29 08:07 UTC, allejo requested changes
I can't press the right button...

2021-05-29 20:33 UTC, Adwitiya-Singh commented on src/Components/Panels/Toolbox/PassabilityControl.tsx
> +  };
Inlining it like `drivethrough: !data.drivethrough` doesn't seem to work.

2021-06-01 00:43 UTC, allejo commented on src/Components/Panels/Toolbox/PassabilityControls.module.scss
> +  margin: auto 0;
```suggestion
```

This isn't needed because the Toolbox parent will take care of this

2021-06-01 00:43 UTC, allejo commented on src/Components/Panels/Toolbox/PassabilityControls.module.scss
> +  width: auto;
```suggestion
```

Let the default vault of `width: 100%` from the Bootstrap Reboot stylesheet take effect here

2021-06-01 00:45 UTC, allejo approved these changes

2021-06-01 00:47 UTC, merged